-- migrate:up
CREATE SCHEMA IF NOT EXISTS auth;

CREATE TABLE IF NOT EXISTS auth.users (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id text UNIQUE NOT NULL,
    email text UNIQUE,
    first_name text,
    last_name text,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

INSERT INTO auth.users(external_id, email, first_name, last_name) VALUES
  ('auth0|user-1', 'test1@test1.com', 'Test1', 'User'),
  ('auth0|user-2', 'test2@test1.com', 'Test2', 'User'),
  ('auth0|user-3', 'test3@test1.com', 'Test3', 'User');

GRANT USAGE ON SCHEMA auth TO application_user;
GRANT SELECT ON auth.users, auth.users_id_seq TO application_user;


-- migrate:down
DROP TABLE IF EXISTS auth.users;
DROP SCHEMA IF EXISTS auth;
